{% set name = "banks" %}
{% set version = "2.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/banks-{{ version }}.tar.gz
  sha256: d1446280ce6e00301e3e952dd754fd8cee23ff277d29ed160994a84d0d7ffe62

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - griffe
    - jinja2
    - pydantic
    - deprecated
    - platformdirs

test:
  imports:
    - banks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A prompt programming language
  home: https://github.com/masci/banks
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
