schema_version: 1

context:
  name: banks
  version: "2.4.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/banks-${{ version }}.tar.gz
  sha256: b3628ac72356396693068fdc6ff8bb5fa63290fad65b9544a06f72cf7fab1d99

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - filetype >=1.2.0
    - python >=${{ python_min }}
    - griffe
    - jinja2
    - pydantic
    - deprecated
    - platformdirs

tests:
  - python:
      imports:
        - banks
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: A prompt programming language
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/masci/banks

extra:
  recipe-maintainers:
    - jan-janssen
