schema_version: 1

context:
  name: banks
  version: 2.5.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/banks-${{ version }}.tar.gz
  sha256: a7ca5c250b605ae90cfd6e4ca5dd6ce2ee377d5d59021b6feba44e345910026d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - filetype >=1.2.0
    - python >=${{ python_min }}
    - griffe
    - jinja2
    - pydantic
    - deprecated
    - platformdirs
    - typing_extensions
tests:
  - python:
      imports:
        - banks
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: A prompt programming language
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/masci/banks

extra:
  recipe-maintainers:
    - jan-janssen
